import { Outfit, Ovo, Poppins } from "next/font/google";
import "./globals.css";

// const outfit = Outfit({
//   subsets: ["latin"], weight: ["400", "500", "600", "700"]
// });

// const ovo = Ovo({
//   subsets: ["latin"], weight: ["400"]
// });

const poppins = Poppins({
  subsets: ['latin'], weight: ["400", "500", "600", "700", "800"]
});

export const metadata = {
  title: "Portfolio - Rayhan Fahlevy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${poppins.className} antialiased leading-8 overflow-x-hidden`}
      >
        {children}
      </body>
    </html>
  );
}

// ${outfit.className} ${ovo.className}